var MyApp = MyApp || {};

MyApp.language = {
    'appname' : 'Room Reservation',
    'fullcalendarlang' : 'en-gb',
    'reservationinformation': 'Reservation Information',
    'setreservationinformation': 'Set the subject of your reservation',
    'reservationday': 'Reservation Day',
    'setreservationday': 'Set the reservation day',
    'starthour': 'Start Hour',
    'selectstarthour' : '- Select Start Hour -',
    'endhour': 'End Hour',
    'selectendhour' : "- Select End Hour - ",
    'alldayreservation': "All Day Reservation",
    'roomsavailable': "Available Rooms",
    'doreservation': "Do Reservation!",
    'description': 'Description',
    'capacity': 'Room Capacity',
    'titlemessage': 'Information Message',
    'doesntexistmessage': 'The Calendar and Resources lists don\'t exist.',
    'advertisementmessage': 'Do you want to create now?. Push "Create" Button',
    'create': 'Create',
    'noroom': 'There are no rooms available at this moment.',
    'succesful': "lists have been created successfully!!!",
    'errorfield': "error adding list fields",
    'errorlist': "error creating lists",
    "subjectneeded" : "You have to set the subject of your reservation",
    "dayneeded" : "You have to set the reservation day",
    "startneeded" : "You need to speficy the start hour",
    "endneeded" : "You need to speficy the end hour",
    "roomneeded": "You have to set the room selected",
    'done': "Reservation correctly done!",
    'fail': "Reservation couldn't be done!",
    'nonselected': 'Room Selected: - None -',
    'selected': 'Room Selected',
    'Mo': 'Mo',
    'Tu': 'Tu',
    'We': 'We',
    'Th': 'Th',
    'Fr': 'Fr',
    'Sa': 'Sa',
    'Su': 'Su',
    'January': 'January',
    'February': 'February',
    'March': 'March',
    'April': 'April',
    'May': 'May',
    'June': 'June',
    'July': 'July',
    'August': 'August',
    'September': 'September',
    'October': 'October',
    'November': 'November',
    'December': 'December'
}

