var MyApp = MyApp || {};

MyApp.language = {
    'appname' : 'Reserva de salas',
    'fullcalendarlang' : 'es',
    'reservationinformation': 'Información de la Reserva',
    'setreservationinformation': 'Indica el objetivo de la reserva',
    'reservationday': 'Día de la reserva',
    'setreservationday' : 'Indica la fecha de la reserva',
    'starthour': 'Hora de Inicio',
    'selectstarthour' : '- Selecciona hora de inicio -',
    'endhour': 'Hora de Fin',
    'selectendhour' : "- Selecciona hora de fin - ",
    'alldayreservation': "Reservar todo el día",
    'roomsavailable': "Salas disponibles",
    'doreservation': "¡Reservar!",
    'description': 'Descripción',
    'capacity': 'Capacidad',
    'titlemessage': 'Mensaje informativo',
    'doesntexistmessage' : 'La lista de calendario y recursos no existe',
    'advertisementmessage' : '¿Quieres crearla ahora? pulsa el botón Crear',
    'create': 'Crear',
    'noroom': 'No hay salas disponibles en este momento',
    'succesful': "¡Lista creadas satisfactoriamente!",
    'errorfield': "Error añadiendo campos a las listas",
    'errorlist': "Error creando listas",
    "subjectneeded": "Tienes que indicar la información de la reserva",
    "dayneeded": "Tienes que indicar el día de reserva",
    "startneeded": "Tienes que indicar la hora de inicio de lareserva",
    "endneeded": "Tienes que indicar la hora de fin de la reserva",
    "roomneeded": "Tienes que indicar la sala",
    'done': "¡La reserva se ha realizado!",
    'fail': "¡La reserva no se ha podido realizar!",
    'nonselected': 'Sala Seleccionada: - Ninguna -',
    'selected': 'Sala Seleccionada',
    'Mo': 'Lu',
    'Tu': 'Mar',
    'We': 'Mie',
    'Th': 'Ju',
    'Fr': 'Vi',
    'Sa': 'Sa',
    'Su': 'Dom',
    'January': 'Enero',
    'February': 'Febrero',
    'March': 'Marzo',
    'April': 'Abril',
    'May': 'Mayo',
    'June': 'Junio',
    'July': 'Julio',
    'August': 'Agosto',
    'September': 'Septiembre',
    'October': 'Octubre',
    'November': 'Noviembre',
    'December': 'Diciembre'
}

